apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql8
  strategy:
    type : Recreate
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - name: mysql8
        image: mysql:8.0.22
        imagePullPolicy: Never
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: Root0++
          - name: MYSQL_USER
            value: newuser
          - name: MYSQL_PASSWORD
            value: pass@word1234
          - name: MYSQL_DATABASE
            value: Usersdb
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
        
